INSERT INTO ROOM_ATTRIBUTE (room_attribute_id, description)
VALUES
    (UUID(), 'Air Conditioning'),
    (UUID(), 'Free Wi-Fi'),
    (UUID(), 'Ocean View'),
    (UUID(), 'Balcony'),
    (UUID(), 'Pet Friendly'),
    (UUID(), 'Mini Bar'),
    (UUID(), 'Smart TV'),
    (UUID(), 'Private Pool'),
    (UUID(), 'Mountain View'),
    (UUID(), 'Jacuzzi'),
    (UUID(), 'Accessible Room'),
    (UUID(), 'Fireplace'),
    (UUID(), 'Garden View'),
    (UUID(), 'Fitness Center'),
    (UUID(), 'Kitchenette'),
    (UUID(), 'Business Desk'),
    (UUID(), 'Bathtub'),
    (UUID(), 'Family Room'),
    (UUID(), 'In-room Safe'),
    (UUID(), 'City View'),
    (UUID(), 'Coffee Maker'),
    (UUID(), 'Hair Dryer'),
    (UUID(), 'Non-Smoking Room'),
    (UUID(), 'Sofa Bed'),
    (UUID(), 'Work Desk'),
    (UUID(), 'Dining Area'),
    (UUID(), 'Outdoor Seating'),
    (UUID(), 'DVD Player'),
    (UUID(), 'Ironing Facilities'),
    (UUID(), 'Free Parking');

